version: '3'
services:
  app:
    build: ./app
    container_name: app
    command: sh -c "uwsgi --strict --ini uwsgi.ini"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./static_data:/opt/app/static

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    volumes:
      - ./static_data:/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app
    ports:
      - "80:80"

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  static_data:

